### ISSUE TITLE
New version missing and other issues?

### ISSUE THREAD

**Issue by Ilir-Liburn** [tomcl/V2releases#6]
Hello,

Every time I run Viusal2, I get message about new version (v. 1.06.10) available, but there is no release here or somewhere else to download.

Why this tool is not open sourced as it was mentioned earlier? I'm interested in improving it, although It seems I have to learn many things first.

I need instruction which will move bits to the right (source can stay intact), and after moving them left (back to original position), source should be cleared.
To my knowledge, SBFM (and aliases SBFIZ, SBFX, SXTB, SXTH, SXTW) are way to go.
Or is there a better way?

**Comment by tomcl** [comment]
Visual2 is not currently being developed and we do not have resources to do this: we may be able to do so this Summer.

The tech stack is complex, and because instructions are coded (not implemented as tables) it will require F# coding + working tech stack to continue development. In practice, that means reworking the very complex build: it is currently very out of date. Then adding instructions etc.

**Comment by tomcl** [comment]
PS Visual2 is open source already:

https://github.com/ImperialCollegeLondon/Visual2

**Comment by Ilir-Liburn** [comment]
Hello,

Beautiful, now I have to learn F#, always wanted to learn F, not sure about F# ;)
But where is v. 1.06.10? I have to build this version or?

**Comment by tomcl** [comment]
ignore 1.06.1 - it had some different functionality added.
